# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiV46spJA-Ss9V2kO4gA0hi0STfCOU9o
"""

class LiverExpertSystem:
    def __init__(self):
        self.rules = []
        self.knowledge_base = {}

    def add_rule(self, condition, conclusion):
        self.rules.append((condition, conclusion))

    def add_knowledge(self, symptom):
        self.knowledge_base[symptom] = True

    def diagnose(self):
        for symptom in self.knowledge_base.keys():
            for condition, conclusion in self.rules:
                if condition(symptom):
                    print("Tashxis:", conclusion)